# Generated by Django 5.1 on 2024-08-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.reader'),
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
